### ISSUE TITLE
Bookmarks import broken from Android 10

### ISSUE THREAD

**Issue by jj49er** [Slion/Fulguris#140]
# Description
Bookmark import on Android 10 restarts the app.

# Environment
 - Device: LG Escape Plus / HTC One M8
 - OS: Android 10
 - Version: 1.2.8

# To reproduce
1. Go to Setting > Bookmarks
2. Click on Import
3. App restarts

# Expected behaviour
Import file selection dialog should popup.

# Additional context
It works fine on my Asus tablet running Android 5.

**Comment by Slion** [comment]
@jj49er Thanks for reporting that issue. It should be fixed in the upcoming release v1.2.9.
Bookmark backup should go through more changes at some point, see #141.
You will notice that bookmark management is rather basic at the moment. That too should also be improved at some point, see #70.
Happy surfing 🏄
