### ISSUE TITLE
Built-In Download Manager/Grabber For Downloading Files/Videos:

### ISSUE THREAD

**Issue by Jpersh27** [Slion/Fulguris#183]
Hello @Slion I do have another feature request.

• 1- I was wondering if you have any plans of adding a downloading manager to the web browser to grab video files, images Files, etc... on the current webpage you are visiting while browsing.

• I will provide examples from the application IDM+ that has a browser built-into the Download Manager application itself that is based on the Lighting Browser and has a built-in feature that allows you to Grab Videos and Images on current webpage you are visiting and allows you to download them in a variety of different formats. 

![IMG_20210410_205539.jpg](https://user-images.githubusercontent.com/77606699/114288570-2e93fe00-9a3f-11eb-854b-08a0125df84b.jpg)

![IMG_20210410_205552.jpg](https://user-images.githubusercontent.com/77606699/114288572-35227580-9a3f-11eb-9db4-1adae5e859bc.jpg)

**Comment by Slion** [comment]
You will have noticed that there is minimal support for downloads on Fulguris. Basically we simply make use of Android built-in download manager. This was done on purpose so that we can focus on improving the rest of the application.
At some point we may get a chance the improve our download experience but at the moment this is not a priority.
Downloads is one thing and video transcoding is another thing altogether which is even less lickly to be implement anytime soon.

If you want the core functionalities of Fulguris with an improved download manager you may want to look at Styx from @jamal2362.

**Comment by jamal2362** [comment]
Hi @Slion ,

I have done some things in the download manager in Styx, it is very difficult.

The download manager does not run perfectly even now, some downloads cause the browser to crash or the file is not downloaded.

I think the download manager needs to be redone from scratch but I don't have the ability to do that right now.

**Comment by Slion** [comment]
@jamal2362 Thanks for sharing your experience. Yes, implementing a feature rich and reliable download manager is no small task. That's the reason I kept it most simple in Fulguris so far.
