### ISSUE TITLE
Can't download image

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#187]
See:
https://greenscene.co.id/wp-content/uploads/2021/05/Arlong-696x497.jpg

**Comment by jamal2362** [comment]
I can confirm this on Fulguris and Styx.
Stange bug 😦

**Comment by jamal2362** [comment]
By itself, the download should work but is prevented by the download manager because of the certificate see pictures.

Here a logcat:
DownloadManager
[1720] Stop requested with status HTTP_DATA_ERROR: Hostname greenscene.co.id not verified:
    certificate: sha1/Y3GP+9qmPno2rD1vcIEgUGoKq3Q=
    DN: CN=www.greenscene.co.id
    subjectAltNames: [www.greenscene.co.id]

![Screenshot_20210515-203840](https://user-images.githubusercontent.com/15986930/118374638-977e1100-b5bd-11eb-820d-174e1cfdff0e.jpg)

![Screenshot_20210515-204144](https://user-images.githubusercontent.com/15986930/118374717-fb083e80-b5bd-11eb-8414-efc1bc784034.jpg)
