### ISSUE TITLE
Content control filters file should use SwitchPreferenceCompat

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#224]
Instead of having the switch toggle in the edit dialog we should really have those filters files AKA blocklists use SwitchPreferenceCompat. Thus user can easily see which filters are enabled from the list without having to edit them.

**Comment by Helium314** [comment]
I tried this, see https://github.com/Slion/Fulguris/blob/a1546e7c9f42768ca7a0808bfc8ea53972a1a5a3/app/src/main/java/acr/browser/lightning/settings/fragment/AdBlockSettingsFragment.kt#L168

My problem was that I couldn't set the enabled change to only happen when clicking the switch, but the dialog open when clicking on the text.
After noticing the problem I didn't try again. But maybe the fix is easy....

**Comment by Slion** [comment]
To me it is acceptable if you can't change the enabled status without opening the dialog. At least it lets you see it from the list.

**Comment by Slion** [comment]
Still if you find a way to toggle without editing it would be awesome.
Maybe you can put an edit icon in front of the preferences.
If the edit icon is pushed then you go to the dialog.
Otherwise, just toggle.

**Comment by Slion** [comment]
Came across this today. That Dark theme item is what we should have ideally. This is part of Lineage OS so we could take a look at how they did it there.
![Screenshot_20220109-223428_Settings](https://user-images.githubusercontent.com/6508892/148701948-a20933cb-749b-4c9a-9042-66efcc9e1684.png)

**Comment by Helium314** [comment]
I'll have a look at this... LOS is using some different preference, see https://github.com/LineageOS/android_packages_apps_Settings/blob/lineage-18.1/src/com/android/settings/display/darkmode/DarkModePreference.java and `MasterSwitchPreference`
