### ISSUE TITLE
Automatically select URL bar on new tab

### ISSUE THREAD

**Issue by Zero3K** [Slion/Fulguris#232]
It would be nice if it automatically selected the URL bar on a new tab to allow entering of a URL as soon as one is made by tapping the + icon.

**Comment by Slion** [comment]
While tempting I don't think that makes much sense. Some people may just want to access a bookmark rather than type in a URL.
Also I'm guessing you have enabled the new tab menu option and maybe disabled 'URL in new tab'.
Fulguris default settings are such that you don't need a new tab option. Just type in your URL and it will create one for you.
It seems you are going against that concept and then asking for a feature to optimize your specific workflow.
That proposed feature would save you one tap on the screen.
The default workflow goes further than that it saves you two taps.

What I'm assuming you do is:
* Tap to open menu
* Tap to select new tab
* Tap text field to type URL

What your proposed feature would do:
* Tap to open menu
* Tap to select new tab and type URL

What Fulguris default workflow does:
* Tap text field to type URL

**Comment by Slion** [comment]
> I tap the plus button. Naked Browser does what I am requesting.

I see, I even forgot there is this new tab plus button in the tabs list. I never use it. As described above you don't actually need it. New tabs are spawned for you. The downside is that from time to time you may want to close tabs you don't need anymore. Moreover you will find Fulguris can deal efficiently with a large amount of tabs.

**Comment by Zero3K** [comment]
What do you mean I don't need it?

**Comment by Slion** [comment]
> What do you mean I don't need it?

It all explained above I believe.

**Comment by Cwpute** [comment]
> It seems you are going against that concept and then asking for a feature to optimize your specific workflow.

While this is true, this is not such a "specific" workflow as Fulguris also provides ways to open new tabs without this feature (from the tabs menu, and from the main menu as well).

Going by this reasoning, Fulguris should either fully support both ways of opening tabs — with qol changes such as requested above being considered — or fully commit to creating tabs by sending querries from the search bar.
