### ISSUE TITLE
Conflict between Fulguris and Styx

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#257]
On this issue we will attempt to find peaceful solutions concerning the on going conflict between Fulguris and its disconnected fork [Styx](https://github.com/jamal2362/Styx). I'll post here a summary of the situation whenever I get a chance.

## References
* [Basis of the conflict](https://github.com/Slion/Fulguris/issues/178#issuecomment-944982786).
* [Relicensing as CPAL-1.0](#256)

**Comment by jamal2362** [comment]
# First of all thank you for talking to us!

A number of points were taken care of by me.
I have revised the complete readme. I put Fulguris at the top so that people loading into the Styx repository can see that it is a fork of Fulguris.

Also, my goal has always been not to monitarize Styx or make money, because it is disrespectful to do so since I am only a fork of Fulguris.

From my side Styx is done, the only thing I still do is to keep it on par with Fulguris. Means if Fulguris has commits then I take them over to Styx.

How do you imagine it in the future so that it comes to no more problem? I want to avoid trouble... Really.

You wrote:
> 
>     * Code is copied from Fulguris and pasted in Styx code base, in the process actual author name is replaced with your name.
> 
>     * No effort is made of your part to contribute back to the Fulguris code base.
> 
>     * Over the months were you kept feeding on that code base you made no effort to promote Fulguris beyond the legally binding.
> 

### Point 1: 
Yes, Styx uses the commits of Fulguris to be always on the same stand as Fulguris. Because it is a fork.
What exactly is meant by the author name?
What should I do ?
Do you mean when I make a commit that I mention your name in the commit ? 
I hope I understand correctly what you mean. If not then correct me.

### Point 2: 
I am ready to do this. You just have to tell me what you want from my additional code besides Fulguris.
I would be willing to make a pull request to your project.
I just never knew what you really wanted in Fulguris, that's why pull requests never came from me.

### Point 3: 
This problem should be fixed now. I have changed the readme so that other users of Styx see that they should support Fulguris.
Your name is available in the "License" and in the Styx App under "About" Fulguris is at the first place for the Credits.
Also fulguris is now in the first place in the readme and that's good because without fulguris Styx wouldn't exist.
Are there any improvements I could make ?

# I hope I have answered the questions well.

**Comment by jamal2362** [comment]
One thing I overlooked that I only saw now is this with the welcome screen with the hint of "Powered by Fulguris".

Is this desired ? 
If so then please let me know and I will start to implement this in Styx.

**Comment by Slion** [comment]
I did not read all of that yet but it looks like we are making amazing progress here. I'll come back to you once I get around it.

**Comment by jamal2362** [comment]
That is good thank you.

**Comment by Slion** [comment]
> I have revised the complete readme. I put Fulguris at the top so that people loading into the Styx repository can see that it is a fork of Fulguris.

Thanks, that's the first thing I noticed. It's awesome, it's almost too much 😁 I guess there is no need to put the Fulguris Google Play badge there. Prominante attribution and link to the Fulguris GitHub home page should do just fine. Now exactly which form that should take still has to be defined. I guess my work on the  CPAL license definition will help here.

**Comment by jamal2362** [comment]
@Slion 
That's not a problem I'm happy to do that. 🤗
I removed the Google Play Store badge and it's linked on their Fulguris GitHub page.

Are there any other changes I should do? If so, let me know. Preferably point by point so I can work through this.

**Comment by Slion** [comment]
> Also, my goal has always been not to monitarize Styx or make money, because it is disrespectful to do so since I am only a fork of Fulguris.

Monetizing to me is an important part of that venture as that's the best way to guarantee long term sustained sucess. However it will not be achieved through data collection or intrusive ads. At the moment it's only subscriptions and donations and amounts next to nothing. On the other hand I reckon I invested around 60k euros mostly in engineering hours. Let's face it however it's very unlikely it will ever become profitable.

**Comment by Slion** [comment]
> From my side Styx is done, the only thing I still do is to keep it on par with Fulguris. Means if Fulguris has commits then I take them over to Styx.

There is a lot still to come on the Fulguris roadmap. Some of it has already been documented and is being tracked on the [project page](https://github.com/Slion/Fulguris/projects/1). That includes new features, improvements and bug fix as well as just maintenance. That's a lot of work and I can't guarantee I'll be able to go through it at a sustained pace without proper financing, quite the opposite in fact. Nevertheless, I'm hopeful that if we manage to build a healthy community of contributors here we can keep it up somehow.

I know you want to keep up with Fulguris and get the latest features integrated as soon as possible in Styx and I would expect no less. However you are not being clever about it and that's where this conflict started too. Outside the fact that stripping the authors name is really unwelcome, not to mention possibly illegal, you are investing a lot of time in something that could be done almost automatically. Also the way your are doing it means it's harder for Fulguris to benefit from improvement done in Styx. I'll come back that point later as I would like us to work together to fix that.

**Comment by jamal2362** [comment]
I know I wasn't smart enough in the past but the problem should be fixed now from my side.

I know that I have to enter all the commits manually in Styx. A pull request is therefore not possible because the package name is different and that costs a lot of time. But I have consciously taken that in purchase. How can we fix this problem in the future ?

Where has the author name been missing so far ? If I knew that then I could do this better in the future. So that it comes to no more conflict.

**Comment by jamal2362** [comment]
@Slion 

I have a proposed solution. Each commit of Fulguris that I manually enter in Styx I will store credits in the commits with the name of the creator of the commit.

Then I will make it so that after each app update a notification comes when starting the app with Powered by Fulguris.

Is that ok?

**Comment by jamal2362** [comment]
https://github.com/jamal2362/Styx/issues/99

**Comment by jamal2362** [comment]
@Slion 
Feature is implemented now.
https://github.com/jamal2362/Styx/issues/99

**Comment by jamal2362** [comment]
Updated Issue:
https://github.com/jamal2362/Styx/issues/99

**Comment by Slion** [comment]
> have a proposed solution. Each commit of Fulguris that I manually enter in Styx I will give credits in the commits with the name of the creator of the commit.

Yes that should definitly be done, however I wish we could do better than that at some point.

**Comment by Slion** [comment]
> know that I have to enter all the commits manually in Styx. A pull request is therefore not possible because the package name/folder structure is different

Ideally you should completly change your approach here, you don't need the changes in folder structure, it does no give you anything, it just makes your life harder. Remember that time it took you two weeks to catch up after I made some significant architecture changes in our settings? There are ways to mitigate those problems.

Here is what you should do ideally:
- Pull the Fulguris main branch in your Styx repository maybe name it fulguris.
- That will restore the whole git history from Lightning and Fulguris.
- Then branch it into a styx branch.
- From there add your styx branding as a flavor in the gradle file and associate your package name with.
- Now you should be able to build Fulguris with the Styx package name already.
- From there start adding back your icons and layouts in styx folders corresponding to your flavor. Do not overwrite the Fulguris icons. The styx icons are just going in the proper styx folder.  
- In the same way you can also override the source code you need with your styx source code where needed but here again there are clevers ways to do that to avoid merge conflicts.

It may seems like a lot of work but it should not be that bad and in the long run it will be very beneficial to both projects. Ideally if we do that properly we could merge back most of the Styx changes in the Fulguris code base. We could just build Styx from the Fulguris code base and yet both projects would still be unique much like today.

Hope that makes sense.

**Comment by jamal2362** [comment]
@Slion 
Oh that's a huge change.
I would agree to do this.

I have a question about this.
Will all the changes I have made so far be lost? Does everything remain 1:1 the same as before?

I have read your instructions but I have no idea how to do this because it seems very complicated.

I could write to you privately for this thing on Discord? So that we come faster to the Ergebniss? Here on GitHub it takes too long and it is more difficult.

**Comment by Slion** [comment]
Yes my instructions are not very precise. It's definitely something we should work on together.

**Comment by jamal2362** [comment]
All right. Then get back to me when you're ready so we can do it together.
