### ISSUE TITLE
Do your browser have this bug of adblocker like yuzu browser?

### ISSUE THREAD

**Issue by rustforfuture** [Slion/Fulguris#274]
Hello

Today i just saw this issue in yuzu browser github repo. (From Adguard Team)

https://github.com/hazuki0x0/YuzuBrowser/issues/221

So i wanted to ask you please check if your browser also has this bug in its adblocker implementation (i suspect more about abp syntax blocker but i'm not sure about it)

Just wanted to warn ao may be Adguard won't block your browser also from their servers and also they won't hit that much cost in those mentioned tweets in that issue of yuzu browser.

Best regards :)

------------------------------

BTW, another question, how many rules your adblocker can tolerate and how many rules you think it will work more efficiently?

Thank you very much.

**Comment by Helium314** [comment]
Thanks for forwarding this!
I implemented the blocker based on Yuzu Browser's blocker, and indeed used most of it's code.

I thought I had checked that it doesn't download unnecessarily often, but that was a while ago...
So re-reading the relevant parts:
* update checks are indeed done on browser startup
* Fulguris doesn't use any AdGuard lists by default, but the user can add them
* Lists update once per week by default, but can be set to daily
* there is a check that should avoid re-downloading the list if it wasn't modified: https://github.com/Slion/Fulguris/blob/6fb8864771d56818cd58a22aba308f0122c5d2e8/app/src/main/java/acr/browser/lightning/adblock/AbpListUpdater.kt#L116-L125

My suspicion is that the problem could be located in one of the last two points. Especially the latter if Yuzu is affected as well.

**Comment by Helium314** [comment]
> BTW, another question, how many rules your adblocker can tolerate and how many rules you think it will work more efficiently?

This would depend very much on the rules. Just blocking hosts is very fast, but with patterns that are checked for every URL, the checks can take more (CPU) time.
On my ancient phone (S4 mini) the default lists take less than 1 ms per check. I would expect that time needed per check increases less than linear, so 10 times the length of the default lists is probably fine. Especially if you have a phone that is not 8 years old.

**Comment by rustforfuture** [comment]
> Thanks for forwarding this! I implemented the blocker based on Yuzu Browser's blocker, and indeed used most of it's code.
> 
> I thought I had checked that it doesn't download unnecessarily often, but that was a while ago... So re-reading the relevant parts:
> 
> * update checks are indeed done on browser startup
> * Fulguris doesn't use any AdGuard lists by default, but the user can add them
> * Lists update once per week by default, but can be set to daily
> * there is a check that should avoid re-downloading the list if it wasn't modified: https://github.com/Slion/Fulguris/blob/6fb8864771d56818cd58a22aba308f0122c5d2e8/app/src/main/java/acr/browser/lightning/adblock/AbpListUpdater.kt#L116-L125
> 
> My suspicion is that the problem could be located in one of the last two points. Especially the latter if Yuzu is affected as well.

Sorry
I am not a developer but from your answer if i understood your answer correctly, you solved this problem by checking if there is a update for the filterlist but it won't download the blocklist if user haven't set automati update to lower time than default (1 week).
T

**Comment by rustforfuture** [comment]
> > BTW, another question, how many rules your adblocker can tolerate and how many rules you think it will work more efficiently?
> 
> This would depend very much on the rules. Just blocking hosts is very fast, but with patterns that are checked for every URL, the checks can take more (CPU) time. On my ancient phone (S4 mini) the default lists take less than 1 ms per check. I would expect that time needed per check increases less than linear, so 10 times the length of the default lists is probably fine. Especially if you have a phone that is not 8 years old.

Oh, ao if i understood correctly, how much the processor of the phone be more powerful, it uses less time to process blocklists and blocking so battery usage will be lower (taking account that the cpu be standard and not a power hungry cpu like old nvidia ones ;)

Thank you very much.
In my relatives, probably the newest phone is for 2019😅

But as i mostly use AdBlockPlus versions of hosts file that doesn't have cosmetic rules, probably it will be better for both better performance and lower battery consumption if i be correct (?)

Thank you very much
Best regards.

**Comment by Helium314** [comment]
> Sorry I am not a developer but from your answer if i understood your answer correctly, you solved this problem by checking if there is a update for the filterlist but it won't download the blocklist if user haven't set automati update to lower time than default (1 week).

How exactly it is happening:
When adblocker is started every list is checked whether it should be updated. This means: the last update check was longer than the update interval ago (1 week by default) *and* the blocklist is expired. "Expires" is an (optional) part of the blocklists that basically says how long it should be considered valid (for EasyList this is 4 days).
So if the last update check was more than a week ago and the list is expired, the quoted code is executed. It basically means that we ask the server to send us the blocklist, but only if it has been modified since our last update.

Some tests I did previously (and again yesterday) confirmed the first part is working. I did not test the "If-Modified-Since" part, as this is a standard HTTP header and should work. But since you brought this up I'll check it; a thing that would mess it up could be a wrong date format.

> Sorry for another question, what is the behavior of host based blocker that is based on lightning?

Not sure what you mean here. Is the question about the updating behavior, or about differences in blocking?

> Oh, so if i understood correctly, how much the processor of the phone be more powerful, it uses less time to process blocklists and blocking so battery usage will be lower (taking account that the cpu be standard and not a power hungry cpu like old nvidia ones ;)

Blocklist processing takes *much* less time than the normal website rendering, so I think battery should not be affected at all.
Or maybe battery is even better in case some heavy ad is blocked that would otherwise play a video.

> But as i mostly use AdBlockPlus versions of hosts file that doesn't have cosmetic rules, probably it will be better for both better performance and lower battery consumption.

Yes, if you use a file that only contains hosts there should not be any slowdowns due to checking, even with very long lists.

Cosmetic rules are currently not implemented. They were a bit low on my priority list as they don't affect privacy and I couldn't get the Yuzu implementation working.

**Comment by Helium314** [comment]
Looks like some pages (like github, where we get the Steven Black's hosts list) don't supply a last-modified header, so even unmodified lists are downloaded again at every update interval.
It's far not as bad as re-downloading the list on every browser start, but I think there is nothing I can do here.

**Comment by Helium314** [comment]
I tried setting a fake last-modified date so the `If-modified-since` header is sent. Nevertheless, github sends the (unchanged!) full list instead of response 304 (not modified).

The list gets updated roughly once a week, sometimes more often. We could change the default url to the official alternative http://sbc.io/hosts/hosts, which may provide a `last-modified` header, but there is no https available and I don't really like that.

So I think there is nothing left to do here.

**Comment by rustforfuture** [comment]
> > Sorry I am not a developer but from your answer if i understood your answer correctly, you solved this problem by checking if there is a update for the filterlist but it won't download the blocklist if user haven't set automati update to lower time than default (1 week).
> 
> How exactly it is happening: When adblocker is started every list is checked whether it should be updated. This means: the last update check was longer than the update interval ago (1 week by default) _and_ the blocklist is expired. "Expires" is an (optional) part of the blocklists that basically says how long it should be considered valid (for EasyList this is 4 days). So if the last update check was more than a week ago and the list is expired, the quoted code is executed. It basically means that we ask the server to send us the blocklist, but only if it has been modified since our last update.
> 
> Some tests I did previously (and again yesterday) confirmed the first part is working. I did not test the "If-Modified-Since" part, as this is a standard HTTP header and should work. But since you brought this up I'll check it; a thing that would mess it up could be a wrong date format.
> 
> > Sorry for another question, what is the behavior of host based blocker that is based on lightning?
> 
> Not sure what you mean here. Is the question about the updating behavior, or about differences in blocking?
> 
> > Oh, so if i understood correctly, how much the processor of the phone be more powerful, it uses less time to process blocklists and blocking so battery usage will be lower (taking account that the cpu be standard and not a power hungry cpu like old nvidia ones ;)
> 
> Blocklist processing takes _much_ less time than the normal website rendering, so I think battery should not be affected at all. Or maybe battery is even better in case some heavy ad is blocked that would otherwise play a video.
> 
> > But as i mostly use AdBlockPlus versions of hosts file that doesn't have cosmetic rules, probably it will be better for both better performance and lower battery consumption.
> 
> Yes, if you use a file that only contains hosts there should not be any slowdowns due to checking, even with very long lists.
> 
> Cosmetic rules are currently not implemented. They were a bit low on my priority list as they don't affect privacy and I couldn't get the Yuzu implementation working.

Thank you very much for your very detailed, helpful and kind reply.

Sorry, i has eye issues so i couldn't come sooner.

Thank you very much for your great efforts.
Best wishes.

**Comment by rustforfuture** [comment]
> I tried setting a fake last-modified date so the `If-modified-since` header is sent. Nevertheless, github sends the (unchanged!) full list instead of response 304 (not modified).
> 
> The list gets updated roughly once a week, sometimes more often. We could change the default url to the official alternative http://sbc.io/hosts/hosts, which may provide a `last-modified` header, but there is no https available and I don't really like that.
> 
> So I think there is nothing left to do here.

Yes, completely agree, https version is better.

Thank you very much for spending this much time to investigate and check all these again.

You are really great :)
Best wishes.
Merry Christmas :)
I wish a great year for you and wish to always be happy and healthy ♥️😊

**Comment by Helium314** [comment]
Turns out in some cases there actually _is_ a problem: If the user has set the update frequency to 1 month, _and_ the server does not provide a last-modifed header, _and_ the list does not have an expires value, the list is updated at every browser start.

This happens because 1 month in milliseconds is too long to be stored in an integer. Will be fixed soon.
