### ISSUE TITLE
Tab problems in latest version

### ISSUE THREAD

**Issue by Helium314** [Slion/Fulguris#315]
When opening a link from a different app, it is opened in a new tab, but the tab is not shown. I need to manually switch to the new tab.
This bug does not occur in older versions like v1.7.21. It does not occur when Fulguris is already running while the link is openend, and I am unable to reliably reproduce it after using the browser some more.
When this bug occurs, there is some related bug where closed tabs are not actually closed. This is easy to reproduce as noted below, but also happens without closing the browser.

More precise steps:
* have latest build (I used the fdroid build)
* clear data of Fulguris (it stops being easily reproducible after some use, didn't do more specific testing)
* open browser (not sure if actually necessary)
* close browser (by swiping away from recents)
* open link in Fulguris (from other app)
* link is **openend behind bookmarks**
* open tab drawer
* swipe away link tab and bookmarks tab
* open Fulguris
* open tab drawer
* see **tab with link still exists**

**Comment by Slion** [comment]
Thanks, another great catch. Version 1.7.25 has seen some significant architecture changes so it's possible we get more of those including crashes.

Looks like we have two issues here:
- Opening a tab from a third-party app when Fulguris is not running opens it in the background. I also noticed that closing that tab sends us back to the app that opened it. Though I'm thinking this a feature rather than a bug.
- Closing the last tab from a saved session does not empty that session.

**Comment by Slion** [comment]
I've opened #316 and #317 to tackle those issues.
