### ISSUE TITLE
Open in new tab and close current tab

### ISSUE THREAD

**Issue by Justauser0** [Slion/Fulguris#475]
Like this

![IMG_20230625_123851](https://github.com/Slion/Fulguris/assets/135147872/6ab9fd94-c7f6-458f-8f8e-d8401e061de2)

**Comment by Slion** [comment]
What's wrong with just clicking on the link?

**Comment by Justauser0** [comment]
Removing manually is pretty boring

**Comment by Slion** [comment]
That's not a very common use case though is it?

**Comment by Slion** [comment]
I'll close and postpone this as I don't think that's a common use case for most people.
The only thing it does from just clicking on the link is removing the tab history.
Please feel free to explain further why this is something that you would like so that we can better understand the need for it.
Thank you very much for your feedback. Hope that does not put you off from contributing more ideas.
