### ISSUE TITLE
Discussion: UX/UI proposals regarding Domain settings

### ISSUE THREAD

**Issue by Cwpute** [Slion/Fulguris#514]
*_EDIT:_ this issue is a mix of many issues and suggestions, i will open individual issues adressing each part of my original post as i see fit.*

With the new Domain specific parameters rolling out recently, i was quite excited to see how it would be presented and affect my daily use of Fulguris, as to my knowledge, this is a pretty rare feature, and only the second time i see it implemented in an Android web-browser.
Unfortunately i found it difficult to understand where to find said parameters and the way they were presented was far from satisfactory, and i feel it needs to be properly adressed. So i took it upon myself to write down my gripes about it, and present several changes that could help alleviate the issues.

UX and UI are not easy to get right, but i'll try my best at explaining why i'm advocating for each change i'll present for review regarding this issue.

*So let's get going!* 🤓

Currently the Domain settings are located under the fulguris menu button `⚡` > `Options` > `Domain`. This can be confusing for two reasons:
1. `Options` is located right under `Parameters`. The difference between options and parameters isn't clear right away, so searching for any mean to… modify how Fulguris behaves, which section should i explore ? Furthermore there is this `Webpage` section. Is it not a page i'm browsing right now, so should i explore this section instead? It is super confusing, especially fwr new users, where the domain options will be found.
2. I bet most end users don't know what a domain name even is, so searching for options about something you don't know the proper, technical name of is rather confusing. Granted, there is a little description below the section's title but it isn't of much use.

Let's start with problem #2: 
- [ ] Change the word "domain" for something more popular.
I think it'd be much more clear if the menu section for domain specific options was called "Options for current Website" or "Website options" or even "Customize website".
When people think of different pages scattered across and spannig the same domain, most will refer to that collection of pages as a "Website" rather than a "Domain". While this may not be an entirely accurate word, it's definitely the most used out there, to my knowledge. So when searching for options to modify how that collection of pages is presented, i'd expect people to understand it better if they were presented with a section called `Options for this Website` or something like that.
On another note, maybe the intent when creating the `Webpage` section was for it to later become the domain options section, as it serves a similar purpose with its quick settings regarding reader mode, dark mode etc… but with this new feature, i feel this section's name ups the confusion even more. I'll adress this issue later in this post.

Now to tackle problem #1, here is a combination of modifications that would helb:
- [ ] Remove entirely the `Options` section, as it is redondant and confusing.
- [ ] Remove the `Scrollbars` settings from the `⚡` menu button: not much use having it as a "quick" tool, as you mostly set it up once and forget about it. Its place is in the Parameters sub-menu, where all other app-wide parameters are located.
- [ ] Move the domain options section at the root of the `⚡` menu, just like it was set up after the first update that introduced it, so it is always visible and quickly accessible for instant tweaks to the curently used domain.

Now back to that `Webpage` section we talked about. Its contents currently conflict with what can be found in the domain options section, so here are changes that should help:
- [ ] Remove tab-specific options `Content control`, `Dark mode`, and `Desktop` from the `Webpage` menu, as they are confusing and redundant as to what they affect compared to domain options. These feel like band-aids now compared to how the domain options work.
- [ ] Rename `Webpage` section to `Tools`, to avoid confusion between the words and concepts of webpages, domains and websites. Also, "Webpage" doesn't describe what its content are but rather what  theme ties them all together, whereas "Tools" is a lot more explicit in the purpose of the handy options located in this section.

In the following changes, i try to communicate better to the user how domain options work.
As i stated previously, a "domain" in itself isn't something most people know about right away, so domain specific options might not be very self-explanatory. The way it works right now is that it overrides other app-wide parameters or domain specifics upon user request. Should users specifically know about it ? What we want to see is the website change from light to dark, or from smartphone to computer-adapted, the details don't matter.

- [ ] In the domain options section, remove all of the `Override` toggles
They don't serve much purpose: if a user wants to change how a website behaves, they change its options, which overrides the defaults whatever happens. What's the purpose of this toggle then, repeated for each domain option ?
If its purpose is to allow users to revert to the default parameters for that domain, i think a domain-wide `Reset to default` button would do. How i imagine this is that people will try out options that will or will not please them, one after the other, and if it doesn't work out for them, resetting the whole domain options to zero would just be quicker. Or if they iterate on options one by one, the current toggles will only slow them down. Either way, i don't feel they serve a very distinct purpose.
- [ ] Make it appearant that changes have been done to the default options of the current website's domain.
I can see myself setting up domain specific options and forgetting about it, the coming back to that website after some time and being surprized it's in an unusable state (because of an update in the way Fulguris hadles domain options, an update in the website contents itself…). To prevent that, we could have the domain options section logo or text differ between an untouched and tampered website: a change in text colour and/or logo colour, a change of logo (from a lone wrench to the same wrench embedded in a plain white circle, a checkbox with and without a checkmark) are some examples i can think of.

Finally, here are other small oddities that could be fixed:
- [ ] Edit the domain adress by tapping the `Domain` button in the domain options section.
Currently, this action open a new tab with that adress. What's the use case ? if there isn't any, i'd suggest replacing it with manual editing of that domain adress, for more precise customization.

_Phew!_
I didn't expect it to be such a wall of text, i hope its all understandable. Other things might come to my mind later on, but i'll add them later.

Feel free to give your own insight as an end user so we better understand how the Domain parameters feature is used and will be used !
What i'm giving here are proposals as to how i'd see the menu be laid down to us, and can be disagreed with and iterated upon, as you do with suggestions.

**Comment by Slion** [comment]
Thanks for the feedback. I have not read it all thouroughly yet but here are some explainations.
Did you try hierachical domain settings from v1.9.4 before writting that piece?

# Options, Settings, Web page and Main menus

The new Options menu will offer access to contextual parameters such as domains settings and live parameters such as scrollbars. At the moment it provides access to domain settings for the page you are currently look at. That saves you from having to go look-up domains yourself through the Settings. It also provides access to scrollbars options thus as you adjust those settings you can see how it looks as it is applied to the UI underneath. When I get to it, more of the Look & Feel settings will move or be duplicated into the Options menu. Both domain and scrollbars options can also be found in the Settings.
The Options menu should not contain stuff you want to have quick access to. It's just a more user friendly version of the Settings if you want. Neither scrollbars nor domain settings is something you need quick access to during a typical browsing session. 

The Web page menu could also be called Tab menu I suppose. It offers contextual actions for the current tab. It was created to declutter the Main menu and still serves this purpose well. Changing a domain option from that menu, such as dark mode for instance will only apply to that tab. It's also not persisted ATM so restarting the browser will reset dark modenfor that tab to its domain settings.

The Main menu is just an entry point to access various app level features.

# Domain vs Site

Chromium does offer domain settings, they call it site settings. I'm not ruling out using that same vocabulary at some point. It is definitly more user friendly than domain. We could indeed refer to site and sub-site instead of domain and sub-domain. It would make it easier for translators too.

# Override

Override is needed if you want your default settings changes to apply to all known domains. It does make the UI chunky however and I was already putting some thought on implementing a custom UI for it. Still I think it will remain like that for the time being. Chrome as something similar to what you are suggesting with a clear and reset button. That also means Chrome does not let you override settings for each domain.

# Please

You may want to open dedicated issues for the points I have not addressed yet. It's a lot easier to discuss and track things down when you split them up in dedicated focused topics.

**Comment by Cwpute** [comment]
I'm sorry to have reported so many things at the same time, it only feels issue brings anotger one regarding a similar topic. I guess i should have opened a discussion board for Ui and Ux matters in general, then have reported each suggestion as their separate issue.
I will try to do just that and link all of them to here.

**Comment by Cwpute** [comment]
Done 🥵
i'll close this as completed to prioritize the new separate issues.

**Comment by Slion** [comment]
Merci 😁 C'est beaucoup de travail tout ça, pour toi, comme pour moi 😰 Je vais essayer dit regarder de plus près mais petit à petit. C'est pas comme si j'avais déjà pas assez de boulot 😅
