### ISSUE TITLE
Change Domain URL button use in Domain submenu

### ISSUE THREAD

**Issue by Cwpute** [Slion/Fulguris#520]
Currently,  the Domain button in the domain options submenu opens a new tab with that URL. What's the use case ? It feels useless at best, or confusing at most.
if there isn't any use case , i'd suggest replacing it with manual editing of that domain adress, for more precise customization, or for the ability to browse the currently user-parametered domains.

This suggestion was evoked in #514 before.

**Comment by Slion** [comment]
The purpose of it was mostly to display the name of the domain your are currently changing settings for. That's notably needed in Options where there is no title bar. The link itself is a bonus. Though I too find it anoying maybe it should just copy the domain name instead of opening a tab. I guess this option could be hidden altogether from the settings now that the breadcrumbs are working properly.

**Comment by Slion** [comment]
Actually I just used that link on a domain and I got to do some great reading. I quite like the fact that going through your domains settings you can get an easy opportunity to vist them. Yes it can be annoying when you click it by mistake but I can live with that.

**Comment by Cwpute** [comment]
I find it funny, because the link you can click on that domain button is the same domain as the page you're curently browsing, which renders opening that page almost useless… so that's a veeery edge case of you being distracted by a missclick AND being ok about it !

**Comment by Slion** [comment]
> I find it funny, because the link you can click on that domain button is the same domain as the page you're curently browsing, which renders opening that page almost useless… 

Does not have to be the same page though. It takes you to the root of the domain.

>  so that's a veeery edge case of you being distracted by a missclick AND being ok about it !

Just don't click on it if you don't need it. If user hits it by mistake too bad, they will know better next time. That's more an issue about them and the Android preference screens really. What I could do is make it so that you need to click on the icon to open the link. That would be less error-prone.
