### ISSUE TITLE
infinite loop verfication_ gitlab.com

### ISSUE THREAD

**Issue by ghost** [Slion/Fulguris#524]
@Slion 
* samsung internet_ 21.0 successful login
* 1.9.4 fdroid_ infinite loop verfication, unable 
to login_ gitlab.com
* os: android 9

**Comment by Slion** [comment]
Which version of WebView are you running? I just tested that and I could login on gitlab.

**Comment by Slion** [comment]
It sounds like a problem with your WebView. See if you can update it somehow. That's why you are having the same issue with CookieJarApps/SmartCookieWeb#318.

WebView v103 is relatively old. The current one is v115. Make sure Chrome is up to date and/or the WebView itself too. See if you can change your WebView provider through the WebView DevTools but that is not usally possible unless you rooted and patched your device. You can open the DevTools from Fulguris WebView Settings.

https://play.google.com/store/apps/details?id=com.google.android.webview
https://play.google.com/store/apps/details?id=com.android.chrome

I'll close that ticket as this is surely WebView related.

**Comment by Slion** [comment]
Glad you could upgrade your WebView. That's weird that it is still happening. 😅
