### ISSUE TITLE
Enable cookies as domain settings

### ISSUE THREAD

**Issue by josephg5** [Slion/Fulguris#550]
Hope title is concise yet descriptive enough.

**Comment by Slion** [comment]
There was already a couple of cookies related tasks on #159. I just added a new one and will close this as duplicate.

**Comment by Slion** [comment]
You would have noticed v1.9.14 now has third-party cookies as domain settings. However I'm not sure I can do the same reliably for the rest of the cookies. The cookies setting itself applies to all WebView and since we can have multiple WebView from different domains running at the same time I'm concerned it just won't work properly.
