### ISSUE TITLE
Dark mode does not display some sites correctly

### ISSUE THREAD

**Issue by alan-ford** [Slion/Fulguris#572]
# Description
Dark mode does not display some sites correctly.

# Environment
 - Device: Amazon Fire 7
 - OS: Lineage 14.1 (Android 7.1.2)
 - Version: 1.9.15

# To reproduce
Steps to reproduce the behaviour:
1. Menu > Settings > Domains > Default > Force dark mode
2. Open [https://www.animeclick.it/](https://www.animeclick.it/)

# Expected behaviour
Correct display of sites even with dark mode enabled.

# Screenshots
Left: dark mode enabled
Right: dark mode disabled

![ful](https://github.com/Slion/Fulguris/assets/44990009/f0b777bb-2f6d-45c7-9af4-8150a2c9215f)

**Comment by Slion** [comment]
It's a WebView issue. It works fine on newer WebView such as v117. I can reproduce the issue on Android 6 with WebView v96. Nothing we can do about at I'm afraid. See if you can update your WebView or maybe try to use rendering modes instead of dark mode. Settings / Look & feel / Web page / Rendering mode.
